Auto align
FRC-7525/2024-Rewrite pull request #16
Opened 2024-08-01 22:23 UTC by PotmanNob

Implemented auto aligning that is controlled with the secondary controller.

LB/RB : go to set point. After the robot reached it's setpoint, drive controls will be returned.

X: cancel auto-align

2024-08-02 04:12 UTC, GreenTomato5 commented
You should have button presses linked to amp poses (like A on secondary controller or something)  and you should also automatically shoot when you reach the setpose (either into the amp or shooter) so you should have a setstate function in manager or something of the sort

2024-08-02 04:14 UTC, GreenTomato5 requested changes

2024-08-02 04:14 UTC, GreenTomato5 commented on src/main/java/frc/robot/Constants.java
> +    public static final PIDController ROTATIONAL_VELOCITY_CONTROLLER = new PIDController(5, 0, 0);
generally its best practice to use a PIDConstants object to store PID values in constants. You also only really need 1 translation PID controller because the same motor controls X and Y translation

2024-08-04 02:03 UTC, GreenTomato5 requested changes
😭

2024-08-04 02:03 UTC, GreenTomato5 commented on .github/workflows/format.yml
why did bro delete this 😭

2024-08-04 02:03 UTC, GreenTomato5 commented on .github/scripts/constants.py
> -excused_files = ["Constants.java", "BuildConstants.java", "LocalADStarAK.java", "ModuleIOSparkMax.java", "ModuleIOTalonFX.java", "PhoenixOdometryThread.java", "SparkMaxOdometryThread.java"]
should include SparkMaxOdometryThread.java

2024-08-04 02:03 UTC, GreenTomato5 commented on .gitignore
> -node_modules/
re-add

2024-08-04 14:58 UTC, closed without merging

2024-08-04 14:59 UTC, PotmanNob commented
this branch is too cursed