added amp bar io abstraction
FRC-7525/2024-Rewrite pull request #6
Opened 2024-07-19 16:51 UTC by PotmanNob

added amp bar code
the parameters for arm sim and DCmotor sim are random values

2024-07-19 18:33 UTC, GreenTomato5 requested changes
Great job, some changes to make

2024-07-19 18:33 UTC, GreenTomato5 commented on src/main/java/frc/robot/subsystems/ampBar/AmpBarIO.java
> +    public Pose3d mechanismPose3d;
No need to log this again, you already log the Pose3d in the periodic of AmpBar.java

2024-07-19 18:33 UTC, GreenTomato5 commented on src/main/java/frc/robot/subsystems/ampBar/AmpBarStates.java
> +    SHOOTING(-0.717, 0, "Shooting Amp"),
Spinner Wheels Should be on in the shooting state

2024-07-19 18:33 UTC, GreenTomato5 commented on src/main/java/frc/robot/subsystems/ampBar/AmpBarStates.java
> +    OUT(-0.717, 0, "Amp Bar Out"),
Because we probably arent integrating the climber into this rewrite we don't really need an out state for the amp bar. This state is also the same as "holding note".

2024-07-19 18:33 UTC, GreenTomato5 commented on src/main/java/frc/robot/subsystems/ampBar/AmpBarIOReal.java
> +        controller = new PIDController(1, 0, 0);
The PID controller shouldn't be directly configured in the IO abstraction with actual values. You should initialize it as a PID controller with kP kI and kD set to 0 with the assumption that io.configurePID(number in here) gets called when an instance of AmpBar gets created (with the switch statement and whatnot so you can easily switch PID controllers across different modes)

2024-07-19 18:33 UTC, GreenTomato5 commented on src/main/java/frc/robot/subsystems/ampBar/AmpBarIOReal.java
> +            new Translation3d(0,0,0),
You already log this in AmpBar.java in periodic

2024-07-19 18:33 UTC, GreenTomato5 commented on src/main/java/frc/robot/subsystems/ampBar/AmpBarIOReal.java
> +        leftMotor.set(pivotMotorAppliedVoltage);
should use setVoltalge() to be consistent with sim

2024-07-19 18:33 UTC, GreenTomato5 commented on src/main/java/frc/robot/subsystems/ampBar/AmpBarIOReal.java
> +        spinnerMotor.set(speed);
Also use setVoltage() here to be consistent with sim

2024-07-19 18:33 UTC, GreenTomato5 commented on src/main/java/frc/robot/subsystems/ampBar/AmpBarIOSim.java
> +            Math.PI,
Random values are fine but im pretty sure having the max and min angle as the same value will make the sim just not work

2024-07-19 18:33 UTC, GreenTomato5 commented on src/main/java/frc/robot/subsystems/ampBar/AmpBarIOSim.java
> +            new Rotation3d(0, getPivotPosition(), 0)
Again you already log this in AmpBar.java in periodic

2024-07-19 18:33 UTC, GreenTomato5 commented on src/main/java/frc/robot/subsystems/ampBar/AmpBarIOSim.java
> +        pivotAppliedVoltage = controller.calculate(pivotSim.getVelocityRadPerSec() * 60, pivotSetpoint);
you should use pivotSim.getAngleRads() because you're not trying to spin the pivot, you just want to get it to a specific point. To also get the real pivot units in rads you can add the following lines to the real sim constructor instead of using the native units (rotations or something)
[yourmotorname].setPositionConversionFactor(2 * Math.PI);
[yourmotorname].setVelocityConversionFactor(2 * Math.PI);

2024-07-19 18:33 UTC, GreenTomato5 commented on src/main/java/frc/robot/subsystems/ampBar/AmpBarIOSim.java
> +    }
To update the sim you have to add 
pivotSim.update(0.05);
spinnerSim.update(0.05);
into the update inputs function which will update the sim at the same speed at the periodic loop. You may also be able to just put it in the constructor because I would assume it runs and whatever rate you set it to when initially calling it but in the advantage kit example they put it in the update inputs function.

2024-07-19 18:33 UTC, GreenTomato5 commented on src/main/java/frc/robot/subsystems/ampBar/AmpBarIOSim.java
> +        return spinnerSim.getAngularVelocityRadPerSec() * 60;
get velocity with the talon in the real abstraction returns rotations per second so you just have to divide this by 2pi (I think)

2024-07-19 18:33 UTC, GreenTomato5 commented on src/main/java/frc/robot/subsystems/ampBar/AmpBar.java
> +        super("AmpBar", AmpBarStates.OFF);
The subsystem name should be "Amp Bar" so any AK logging stuff eventually placed in subsystem.java logs to the same place for a given subsystem that it would from Logger.processInputs

2024-07-19 18:33 UTC, GreenTomato5 commented on src/main/java/frc/robot/subsystems/ampBar/AmpBar.java
> +            io.setSpinnerSpeedpoint(-0.5);
All this logic should be handled in the manager once it gets created by setting the state to holding note and then just shooting. For the amp bar you only have to wait for spinning up during the handoff

2024-07-19 18:33 UTC, GreenTomato5 commented on src/main/java/frc/robot/subsystems/ampBar/AmpBar.java
> +            new Pose3d(new Translation3d(0,0,0), new Rotation3d(0,Units.rotationsToRadians(io.getPivotPosition()), 0))
pivot position should be in rads

2024-07-19 18:33 UTC, GreenTomato5 commented on src/main/java/frc/robot/subsystems/ampBar/AmpBar.java
> +        io.setStateString(getState().getStateString());
This is option but would be pretty cool.  In the subsystem abstraction right now the subsystem state gets logged to smart dashboard. You can add something or replace the smart dashboard logging with Logger.recordOutput(stuff to log the state string) so you don't need this setStateString method

2024-07-19 18:35 UTC, nkalupahana commented on src/main/java/frc/robot/subsystems/ampBar/AmpBarIOReal.java
> +    final double ERROR_OF_MARGIN = 0.1;
guys :(

2024-07-19 18:55 UTC, GreenTomato5 commented on src/main/java/frc/robot/subsystems/ampBar/AmpBarIOReal.java
> +    final double ERROR_OF_MARGIN = 0.1;
Error of margin is S tier, keep it (In constants)

2024-07-20 19:26 UTC, PotmanNob commented on src/main/java/frc/robot/subsystems/ampBar/AmpBarIOReal.java
> +    final double ERROR_OF_MARGIN = 0.1;
Error of margin is goated. stop hating!!!

2024-07-20 21:30 UTC, GreenTomato5 requested changes
2 more changes!

2024-07-20 21:30 UTC, GreenTomato5 commented on src/main/java/frc/robot/subsystems/Subsystem.java
> +        Logger.recordOutput(subsystemName + " State", state.getStateString());
it has to be subsystemName + "/state" for it to go to the right spot

2024-07-20 21:30 UTC, GreenTomato5 commented on src/main/java/frc/robot/subsystems/ampBar/AmpBarIOReal.java
> +        return spinnerMotor.getVelocity().getValueAsDouble();
you get this in radians in sim so this should also return radians (just multiply what ur returning by 2pi)

2024-07-20 21:57 UTC, GreenTomato5 approved these changes

2024-07-20 21:58 UTC, merged